# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# discover Azure inventory
---
- name: APPLICATION OVERLAY | setting key_path
  set_fact: key_path="{{ key_path | default(playbook_dir) }}"

- name: APPLICATION OVERLAY | discovering {{ application }}
  azure_rm_networkinterface_facts:
    resource_group: "{{ specified_resourcegroup.name }}"
    name: "{{ project }}_{{ application }}_{{ item }}_internal"
    tags:
      - Application:{{ application }}
      - Role:{{ role | default('none') }}
      - Tenant:{{ tenant }}
      - Project:{{ project }}
      - Cloud:{{ cloud }}
      - Domain:{{ domain }}
      - Cluster:{{ cluster | default('none') }}
      - Dataflow:{{ dataflow | default('none') }}
  with_sequence: count={{ count }}  
  register: all_vms

- name: APPLICATION OVERLAY | adding all discovered hosts to {{ application }} host group
  add_host: hostname="{{ item.ansible_facts.azure_networkinterfaces.0.properties.ipConfigurations.0.properties.privateIPAddress }}" groupname="{{ application }}" ansible_user="{{ user }}" ansible_ssh_private_key_file="{{ key_path }}/{{ cloud }}-{{ region }}-{{ project }}-{{ application }}-{{ domain }}-private-key.pem"
  with_items: "{{ all_vms.results }}"
